apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-server
  labels:
    app: python-server
    name: python-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-server
  template:
    metadata:
      labels:
        app: python-server
    spec:
      containers:
        - image: nkom/python-server:{{ .Values.appVersion }}
          name: python-server
          ports:
            - containerPort: 8080
