apiVersion: v1
kind: Service
metadata:
  name: python-server
  labels:
    app: python-server
spec:
  type: NodePort
  selector:
    app: python-server
  ports:
    - name: pg-app
      port: 8080
      targetPort: 8080
      nodePort: 30000
